FROM oracle/graalvm-ce:19.3.0-java8

RUN gu install native-image
COPY build/libs/daikon-snap.jar /app.jar
#RUN native-image --no-fallback --report-unsupported-elements-at-runtime -jar app.jar
#RUN native-image --no-fallback -jar app.jar
RUN native-image --report-unsupported-elements-at-runtime -jar app.jar
#RUN native-image --allow-incomplete-classpath --allow-incomplete-classpath --report-unsupported-elements-at-runtime -jar app.jar
#RUN yum install -y libstdc++-static
#RUN native-image --no-fallback --report-unsupported-elements-at-runtime -jar app.jar
CMD ["./app"]
